language: node_js
cache: yarn
env:
  global:
  - COMMIT_AUTHOR_EMAIL: travis@gh-pages
  - COMMIT_AUTHOR_NAME: Travis CI
  - SOURCE_BRANCH: master
script:
- yarn lint
- yarn test
after_success:
- bash ./deploy/gh_pages.sh
